### ISSUE TITLE
Specify volumeBindingMode:WaitForFirstConsumer in default storage class

### ISSUE THREAD

**Issue by vlerenc** [gardener/gardener-extension-provider-aws#152] opened 2020-08-02 10:10 UTC
/area storage
/kind enhancement
/priority normal
/platform aws

**What would you like to be added**:
PVs shall be created in the zone where the pod will be scheduled to.

**Why is this needed**:
From https://kubernetes.io/docs/concepts/storage/storage-classes/#volume-binding-mode:
> By default, the Immediate mode indicates that volume binding and dynamic provisioning occurs once the PersistentVolumeClaim is created. For storage backends that are topology-constrained and not globally accessible from all Nodes in the cluster, PersistentVolumes will be bound or provisioned without knowledge of the Pod's scheduling requirements. This may result in unschedulable Pods.

We use `Immediate`, but should rather use `WaitForFirstConsumer`, wouldn't you agree?

**Comment by ialidzhikov** [comment] 2020-08-02 10:19
We already use `WaitForFirstConsumer` with the CSI StorageClasses (starting from k/k@v1.18 for provider-aws).

**Comment by ialidzhikov** [comment] 2020-08-02 10:25
StorageClass `.volumeBindingMode` is also immutable.

**Comment by vlerenc** [comment] 2020-09-04 11:13
@ialidzhikov We can change it by deleting and recreating it as we did for the encryption. Same thing.

As for your version comment, so you suggest to not do anything below 1.18? It seems however a relevant problem.

**Comment by ialidzhikov** [comment] 2020-09-07 16:09
> @ialidzhikov We can change it by deleting and recreating it as we did for the encryption. Same thing.

But the encryption PR is not merged, right? Last week I worked on https://github.com/kubernetes/kubernetes/issues/94189 which is caused by recreating the StorageClass from our side and volume expand controller on Kubernete side that assumes that the StorageClass is immutable (won't be recreated). The fact the field is immutable makes me think that there might be something relying on it to be immutable.
I know that it is 1 line change but I am just thinking about some consequences.
@rfranzke any thoughts on this?

**Comment by ialidzhikov** [comment] 2020-09-07 19:33
In sig-storage slack channel I saw recommendations like this one https://kubernetes.slack.com/archives/C09QZFCE5/p1560976384118500?thread_ts=1560972429.116700&cid=C09QZFCE5 .

/cc @msau42 let me know if there is something wrong in re-creating StorageClass with the same name but `volumeBindingMode` set to `WaitForFirstConsumer`.

**Comment by msau42** [comment] 2020-09-08 16:56
I think it is fine to recreate the StorageClass with same name and change `volumeBindingMode`.

Recreating the StorageClass with same name but different plugin may be problematic as you encountered, since all the existing PV objects with that storageclass are now stale.

**Comment by ialidzhikov** [comment] 2020-09-08 17:09
Thank you @msau42 !

**Closed** 2020-09-09 06:15 UTC
Labels: area/storage, kind/enhancement, platform/aws, priority/normal
