### ISSUE TITLE
Scale from zero fails to work on k8s >= 1.18 AWS

### ISSUE THREAD

**Issue by himanshu-kun** [gardener/gardener-extension-provider-aws#364] opened 2021-06-21 17:07 UTC
**How to categorize this issue?**

/area auto-scaling
/kind enhancement
/priority 3
/platform aws

**What would you like to be added**:

AWS CSI driver specific label `topology.ebs.csi.aws.com/zone` needs to be added while creation of machineDeployment . This provider specific label needs to be added by extension-provider-aws until the aws-ebs-csi-driver team fixes and starts using the well known label `topology.kubernetes.io/zone`

**Why is this needed**:

AWS starts using CSI volume provisioners from k8s>=1.18 and the PV needs csi driver specific label to mount to node rather than the well known `topology.kubernetes.io/zone`label. This leads to cluster Autoscaler not scaling up the node from zero in worker pool as the csi driver specific label is not added by anyone.

**Comment by himanshu-kun** [comment] 2021-06-21 17:08
refer https://github.com/gardener/autoscaler/issues/83 for details

**Comment by himanshu-kun** [comment] 2021-06-21 17:09
cc @prashanth26

**Comment by ialidzhikov** [comment] 2021-06-21 17:13
> This provider specific label needs to be added by extension-provider-aws until the aws-ebs-csi-driver team fixes and starts using the well known label topology.kubernetes.io/zone

Can you please link upstream issue?

**Comment by ialidzhikov** [comment] 2021-06-21 17:18
It seems that the issue is fixed in v1.1.0 with https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/773. I already had an open PR for updating to aws-ebs-csi-driver@v1.1.0.
Can you double-check this?

**Comment by ialidzhikov** [comment] 2021-06-21 17:22
So let’s do not introduce any ugly workarounds for now.

**Comment by ialidzhikov** [comment] 2021-06-21 19:33
Sorry, I was wrong with the assumption that the issue is fixed on aws-ebs-csi-driver side. 😞

**Comment by prashanth26** [comment] 2021-06-22 02:08
> Sorry, I was wrong with the assumption that the issue is fixed on aws-ebs-csi-driver side. 😞

Yes, it's still not fixed at the cluster-autoscaler. @himanshu-kun has looked into this by going through the issues at the `aws-ebs-csi-driver`.

**Closed** 2021-06-28 09:31 UTC
Labels: area/auto-scaling, kind/enhancement, platform/aws, priority/3
